# Generated by Django 2.1.5 on 2019-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=50)),
                ('Mobile_No', models.CharField(blank=True, max_length=10)),
                ('Intime', models.TimeField(blank=True, null=True)),
                ('Outtime', models.TimeField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Day', models.CharField(blank=True, max_length=50)),
                ('Pax', models.IntegerField(null=True)),
                ('Status', models.CharField(default='Active', max_length=20, null=True)),
            ],
        ),
    ]
