# Generated by Django 2.1.5 on 2019-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(blank=True, choices=[('H', 'happy'), ('Un', 'unhappy')], max_length=50)),
                ('f_key', models.ForeignKey(null=True, on_delete='models.CASCADE', to='User.Customer')),
            ],
        ),
    ]
