# Generated by Django 2.1.5 on 2019-04-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190402_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('appetizer', 'appetizer'), ('entree', 'entree'), ('dessert', 'dessert'), ('sandwich', 'sandwich'), ('drinks', 'drinks')], max_length=100, null=True),
        ),
    ]
